name: Continuous Integration

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repository code
      uses: actions/checkout@v2 
    
    - name: Run fetch
      run: git fetch --prune --unshallow

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Desarrollo/DC19/Fuentes/DC19-Flask/requeriments/r.txt

    - name: Lint with flaske8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run test
      run: |
        export FLASK_APP=Desarrollo/DC19/Fuentes/DC19-Flask/dc19.py
        export DC19_ADMIN=admin@dc19.org
        export FLASK_DEBUG=1
        export MAIL_USERNAME=app.supp.20@gmail.com
        export MAIL_PASSWORD=appsup20
        coverage run -m unittest discover -s Desarrollo\DC19\Fuentes\DC19-Flask -v
    
    - name: Coverage report
      run: coverage report -m